windows:
  - time-window

  - user-info-win
  - day-win
  - quote-win
  - poweroff
  - logout
  - reboot
  - sleep
  - wifiwidget
  - wifilogo
  - bluetooth
  - bluetoothlogo
  - vologo
  - volnum
  - volup
  - voldown
  - music-cover-win
  - music-info
  - daytime
  - update
  - update-logo
  - volume-number
  - volume-bar
  - volumeup
  - volumedown
  - app-launcher
  - calculator 
  - wallpaper
  - screenshot
  - wlogout
  - resources-window
  - baricons
  - time
  - journal-win
  - pomowin
  - pomotime
  - timer-btn
  - linkwin
  - uptimewin
  - uptimetext
  - uptimehour
  - uptimeminute
  - folderwin
  - tempwin1
  - tempwin2
  - tempwin3
  - temptext1
  - temptext2
  - temptext3
  - temptext4
  - temptext5